[build]
  base = "Columbus-Ewe-Habobor"
  publish = "Columbus-Ewe-Habobor"
  command = "echo 'No build needed'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0"
